spring:
  datasource:
    url: jdbc:mysql://172.17.0.22:3306/exam?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yn7kzMhTAN9p66Uf
  jackson:
    default-property-inclusion: non_null

urule:
  repository:
    databasetype: mysql
    datasourcename: datasource

server:
  port: 8787
